### ISSUE TITLE
API Key Addition and Feedback Link Problems

### ISSUE THREAD

**Issue by Pierre-Otto** [srosro/deepspring-shellmate#143]
I am unable to add an API Key despite numerous attempts. Additionally, the feedback link is non-functional. Therefore, I am posting my issue here.

System Specifications:
Chip Apple M2
Memory ' 24 GB
Serial number X026TL9M6K
macOS Sonoma 14.6.1

Love the product though.
best,

**Comment by Pierre-Otto** [comment]
I have also attempted to generate new API keys on multiple occasions.

**Comment by delattre1** [comment]
Hey @Pierre-Otto ,

Does your OpenAI key have the format 'sk-proj...'?

Also, I've noticed that when I paste my API key into the input field, sometimes the copy/paste action adds some hidden newline characters, making it seem like the field is empty. The key is actually there, but I had to delete the invisible characters to see it properly!

Let me know if this helps. 

Otherwise, feel free to suggest a time for a meeting. I'm available anytime between 9 AM and 5 PM on weekdays, PST, so I can assist you

**Comment by Pierre-Otto** [comment]
Hi @delattre1,

**Thanks so much for taking on my issue taking the time to reply.
I really appreciate it.**

**To answer your first question:**
The API key does have this format 'sk-proj...' ✅

**To answer your second question:**
In response to concerns about potential copy/paste errors, I have generated a new key and verified the integrity of the copy/paste process. However the issue persists.

I am actually unable to validate the API key. A red indicator appears below the text box, signaling that the key is invalid even before I can press "Continue."

I really appreciate your proposal to organise a meeting, we could plan for example, next Monday at 9AM PST = 12AM (ET) if that works for you ?

Thanks so much for your help !

Best,

**Comment by delattre1** [comment]
Sure, @Pierre-Otto, that works for me!

I’ve created the meeting invitation for 9 AM PST next Monday. Here’s the information:

[ShellMate: User Feedback Session with Pierre-Otto](https://meet.google.com/koy-kqeh-mmo)

Google Meet joining info:
[Video call link](https://meet.google.com/koy-kqeh-mmo)
Or dial: (BR) +55 11 4935-2448 PIN: 384 158 049#
More phone numbers: https://tel.meet/koy-kqeh-mmo?pin=8111271007791

**Comment by delattre1** [comment]
Closing this. The issue was that the OpenAI API account required available credits
