### ISSUE TITLE
Refactor Warnings Display: Consider Scrollable or Fixed Banner Approach

### ISSUE THREAD

**Issue by delattre1** [srosro/deepspring-shellmate#146]
These warnings are currently not displayed in the same area as the suggestions and are not scrollable.

![image](https://github.com/user-attachments/assets/3e0bb2f6-36e9-45c0-9fef-a6854470b480)

They remain fixed and only disappear when the issue is resolved. 

### Proposal

- **Option 1:** Refactor these warnings to appear like the other fixed banners (e.g., 'Chat with Makers' or 'CLI is not installed').
- **Option 2:** Make the warnings scrollable, similar to the pro-tips.
- **Option 3:** Explore another approach to improve the user experience.

https://github.com/user-attachments/assets/1456808e-33c0-4eb3-9460-3734c6614b41

**Comment by maryldyer** [comment]
I think we should update the Network Error to be a fixed banner on the bottom (like the CLI error) but leave the other 2 as is. I'm ok with them not looking like the fixed alert banners but they are technically fixed to the bottom and persistent until the issue is resolved (which follows the fixed banner pattern)

**Comment by delattre1** [comment]
Refactored the network error to be just like the CLI error

![image](https://github.com/user-attachments/assets/6a232796-dc72-4f03-a96f-82910608615b)
